spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://java-test-server.mysql.database.azure.com:3306/java-test-database?serverTimezone=UTC&sslmode=required&user=vhcveonfqp&password=Cruzt%244VgISLy1se"
    username: ${DB_USER:vhcveonfqp}
    password: ${DB_PASS:Cruzt%244VgISLy1se}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
